# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 801ff60aa6b1a9ae26dc3ad436110d2e9ecf7bc645abc254ffc987d302975af4dba2e44def5d8569cdb0ff98ab626d1ac17365cae5bbbf46c350666e9d8f0d52
  google_storage_access_key_id: "GOOGF54CJOP2DXKNKZ5HCRDO"
  google_storage_secret_access_key: "+j0lcnN4PKUteTdnEgXqPXWKXYps4r2/Hcs/wpcm"
test:
  secret_key_base: 65df353ac26a54ed51bbb1dca83c19fae91f4c722368a789cde1367c3350c15d3a2c256129ddb858e61c4d8959720f1257094c92134936b3e5c362649d96e748
  google_storage_access_key_id: "GOOGF54CJOP2DXKNKZ5HCRDO"
  google_storage_secret_access_key: "+j0lcnN4PKUteTdnEgXqPXWKXYps4r2/Hcs/wpcm"
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_storage_access_key_id: "GOOGF54CJOP2DXKNKZ5HCRDO"
  google_storage_secret_access_key: "+j0lcnN4PKUteTdnEgXqPXWKXYps4r2/Hcs/wpcm"
